//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcArea
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class Artistas
    {
        public Artistas()
        {
            this.Obras = new HashSet<Obras>();
        }

        public int id_Artista { get; set; }

        [Required(ErrorMessage = "Usuario requerido.", AllowEmptyStrings = false)]
        [MaxLength(30)]
        public string nombre { get; set; }

        [Required(ErrorMessage = "Rut requerido.", AllowEmptyStrings = false)]
        [MaxLength(10)]
        public string rut { get; set; }

        [Required(ErrorMessage = "Nacionalidad requerido.", AllowEmptyStrings = false)]
        [MaxLength(30)]
        public string nacionalidad { get; set; }
    
        public virtual ICollection<Obras> Obras { get; set; }
    }
}
