//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcArea
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Obras
    {
       
        public int CodigoObra { get; set; }
      
        [Required(ErrorMessage = "Artista requerido.")]
        public Nullable<int> id_Artista { get; set; }
      
        [Required(ErrorMessage = "Estilo requerido.", AllowEmptyStrings = false)]
        [MaxLength(30)]
        public string Estilo { get; set; }

        [Required(ErrorMessage = "Dimensiones requerido.", AllowEmptyStrings = false)]
        [MaxLength(30)]
        public string Dimensiones { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }

        [Required(ErrorMessage = "Procedencia requerido.", AllowEmptyStrings = false)]
        [MaxLength(30)]
        public string Procedencia { get; set; }

         [Required(ErrorMessage = "Valor requerido.")]
        public Nullable<int> Valor { get; set; }

         [Required(ErrorMessage = "Usuario requerido.", AllowEmptyStrings = false)]
        public string CuidadosEspeciales { get; set; }
      
        [Required(ErrorMessage = "Valor requerido.")]
        public int id_Recepcion { get; set; }
    
        public virtual Artistas Artistas { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
    }
}
