//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcArea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registros_login
    {
        public int id_registro { get; set; }
        public int id_usuario { get; set; }
        public string fecha { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
