//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcArea
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    
    public partial class Ubicacion
    {
        public Ubicacion()
        {
            this.Obras = new HashSet<Obras>();
        }
    
        public int id_Recepcion { get; set; }
        [Required(ErrorMessage = "Ubicacion requerido.", AllowEmptyStrings = false)]
        [MaxLength(30)]
        public string Ubicacion1 { get; set; }

        [Required(ErrorMessage = "Nombre salon requerido.", AllowEmptyStrings = false)]
        [MaxLength(30)]
        public string NombreSalon { get; set; }

        [Required(ErrorMessage = "Iluminacion requerido.", AllowEmptyStrings = false)]
        [MaxLength(30)]
        public string Iluminacion { get; set; }

        [Required(ErrorMessage = "Obras maximas requerido.")]
        public Nullable<int> ObrasMaximas { get; set; }

        [Required(ErrorMessage = "Tamaño requerido.", AllowEmptyStrings = false)]
        [MaxLength(20)]
        public string Tamaño { get; set; }
    
        public virtual ICollection<Obras> Obras { get; set; }
    }
}
