//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcArea
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Registros_login = new HashSet<Registros_login>();
        }
    
        public int id_usuario { get; set; }

        [Required(ErrorMessage = "Nombre requerido.", AllowEmptyStrings = false)]
        [MaxLength(30)]
        public string nombre { get; set; }
        [Required(ErrorMessage = "Usuario requerido.", AllowEmptyStrings = false)]
        [MaxLength(10)]
        public string usuario { get; set; }
        [Required(ErrorMessage = "Contraseña requerido.", AllowEmptyStrings = false)]
        [MaxLength(10)]
        [DataType(DataType.Password)]
        public string contraseña { get; set; }
        [Required(ErrorMessage = "Correo requerido.", AllowEmptyStrings = false)]
        [MaxLength(30)]
        public string correo { get; set; }
    
        public virtual ICollection<Registros_login> Registros_login { get; set; }
    }
}
